const gender = [
  {
    "title": "Male",
    "value": "m",
  },
  {
    "title": "Female",
    "value": "f",
  }
];

const genderWithAll = [
  {
    "title": "Male",
    "value": "m",
  },
  {
    "title": "Female",
    "value": "f",
  },
  {
    "title": "All",
    "value": "all",
  }
];

const board = [
  {"title": "Board", "value": "board"},
  {"title": "Thokra", "value": "thokra"},
];

const orderBy = [
  {"title": "Class+Roll No", "value": "cls+roll"},
  {"title": "Class+Name", "value": "cls+name"},
];

const medium = [
  {"title": "Hindi", "value": "hin"},
  {"title": "English", "value": "eng"},
  {"title": "Gujrati", "value": "guj"},
];
const attendance = [
  {"title": "Present", "value": "P"},
  {"title": "Absent", "value": "A"},
];
const result = [
  {"title": "Pass", "value": "P"},
  {"title": "Fail", "value": "F"},
];
const account = [
  {"title": "All", "value": "all"},
  {"title": "With", "value": "with"},
  {"title": "Without", "value": "without"},
];

const branch = [
  {"title": "Ahmed Nagar", "value": "ahmed_nagar"},
  {"title": "Akola", "value": "akola"},
  {"title": "Balotra", "value": "balotra"},
];

const classes = [
  {"title": "1 Jain Dharma Parichaya", "value": "1_jd_parichaya"},
  {"title": "2 Jain Dharma Praveshika", "value": "2_jd_praveshika"},
  {"title": "3 Jain Dharma Prathama", "value": "3_jd_prathama"},
  {"title": "4 Jain Dharma Madhyama", "value": "4_jd_madhyama"},
  {"title": "5 Jain Dharma Chandrika", "value": "5_jd_chandrika"},
  {"title": "6 Jain Dharma Visharad", "value": "6_jd_visharad"},
  {"title": "7 Jain Dharma Kovid", "value": "7_jd_kovid"},
  {"title": "8 Jain Dharma Bhushan", "value": "8_jd_bhushan"},
  {
    "title": "9 Jain Siddhyant Prabhakar - Purvarddha",
    "value": "9_js_prab_purvardhha"
  },
  {
    "title": "10 Jain Siddhyant Prabhakar - Uttaraddha",
    "value": "10_js_prab_uttardhha"
  },
  {"title": "11 Jain Siddhyant Ratnakar", "value": "11_js_ratnakar"},
  {"title": "12 Jain Siddhyant Shastri", "value": "12_js_shastri"},
  {
    "title": "13 Jain Siddhyant Shastri - Purvarddha",
    "value": "13_js_shastri_purvardhha"
  },
  {
    "title": "14 Jain Siddhyant Shastri - Uttararddha",
    "value": "14_js_prab_uttarardhha"
  },
];

const exams = [
  {"title": "EXAM JAN-2025", "value": "jan2025"},
  {"title": "EXAM JULY-2024", "value": "july2024"},
  {"title": "EXAM JAN-2024", "value": "jan2024"},
  {"title": "EXAM JULY-2023", "value": "july2023"},
  {"title": "EXAM JAN-2023", "value": "jan2023"},
  {"title": "EXAM JULY-2022", "value": "july2022"},
  {"title": "EXAM JAN-2022", "value": "jan2022"},
  {"title": "EXAM JAN-2020", "value": "jan2020"},
  {"title": "EXAM JULY-2019", "value": "july2019"},
  {"title": "EXAM JAN-2019", "value": "jan2019"},
  {"title": "EXAM JULY-2018", "value": "july2018"},
  {"title": "EXAM JAN-2018", "value": "jan2018"},
  {"title": "EXAM JULY-2017", "value": "july2021"},
];

const copyChecker = [
  {"title": "Aarti Ji Tated", "value": "aarti_ji_tated"},
  {"title": "Akash Ji Chopra", "value": "akash_ji_chopra"},
  {"title": "Alka Ji Mehta", "value": "alka_ji_mehta"},
  {"title": "Anju Ji Bhandari", "value": "anju_ji_bhandari"},
  {"title": "Astha Ji Choudhary", "value": "astha_ji_choudhary"},
  {"title": "Beena Ji Mehta", "value": "beena_ji_mehta"},
  {"title": "Bhagyawanti Ji Salecha", "value": "bhagyawanti_ji_salecha"},
  {"title": "Bhawana Ji Jain", "value": "bhawana_ji_jain"},
  {"title": "Chandralekha Ji Jain", "value": "chandralekha_ji_jain"},
  {"title": "Chotmal Sa Samsukha", "value": "chotmal_sa_samsukha"},
  {"title": "Deepmala Ji Gang", "value": "deepmala_ji_gang"},
  {"title": "Dharam Chand Ji Jain", "value": "dharam_chand_ji_jain"},
  {"title": "Dharmesh Ji Chopra", "value": "dharmesh_ji_chopra"},
  {"title": "Honaji Mishra", "value": "honaji_mishra"},
  {
    "title": "Kajal Ji Deshlahra & Mamta Ji Jain",
    "value": "kajal_ji_deshlahra_and_mamta_ji_jain"
  },
  {"title": "Kajal Ji Deshlahra", "value": "kajal_ji_deshlahra"},
  {"title": "Kanchan Ji Ranka", "value": "kanchan_ji_ranka"},
  ///////////////////
  {"title": "Khushbu Ji Kanuga", "value": "khushbu_ji_kanuga"},
  {"title": "Kiran Ji Dosi", "value": "kiran_ji_dosi"},
  {"title": "Kushbhu Ji Jain", "value": "kushbhu_ji_jain"},
  {"title": "Lavina Ji Chopra", "value": "lavina_ji_chopra"},
  {"title": "Lokesh Ji Kumbhat", "value": "lokesh_ji_kumbhat"},
  {"title": "Mamta Ji Deshlahra", "value": "mamta_ji_deshlahra"},
  {"title": "Manoj Ji Sancheti", "value": "manoj_ji_sancheti"},
  {"title": "Namita Ji Chopra", "value": "namita_ji_chopra"},
  {"title": "Narpat Ji Chopra", "value": "narpat_ji_chopra"},
  {"title": "Navratan Sa Giriya", "value": "navratan_sa_giriya"},
  {"title": "Nidhi Ji Mehta", "value": "nidhi_ji_mehta"},
  {"title": "Nirmala Ji Bafna", "value": "nirmala_ji_bafna"},
  {"title": "Nitika Ji Bagrecha", "value": "nitika_ji_bagrecha"},
  {"title": "Pankaj Ji Gang", "value": "pankaj_ji_gang"},
  {"title": "Pooja Ji Giriya", "value": "pooja_ji_giriya"},
  {"title": "Pooja Ji Gogia", "value": "pooja_ji_gogia"},
  {"title": "Prem Ji Jain", "value": "prem_ji_jain"},
  {"title": "Priyanka Ji Gandhi", "value": "priyanka_j_gandhi"},
  ///////////////
  ///{ "title": "Priyanka Ji Lunawat", "value": "priyanka_ji_lunawat" },
  {"title": "Purnima Ji Gandhi", "value": "purnima_ji_gandhi"},
  {"title": "Rakshita Ji Bafna", "value": "rakshita_ji_bafna"},
  {"title": "Rangroop Sa Daga", "value": "rangroop_sa_daga"},
  {"title": "Reetu Ji Bafna", "value": "reetu_ji_bafna"},
  {"title": "Rekha Ji Surana", "value": "rekha_ji_surana"},
  {"title": "Rita Ji Khwasara", "value": "rita_ji_khwasara"},
  {"title": "Saloni Ji Bafna", "value": "saloni_ji_bafna"},
  {"title": "Sandhya Ji Singhvi", "value": "sandhya_ji_singhvi"},
  {"title": "Sangeeta Ji Kankariya", "value": "sangeeta_ji_kankariya"},
  {"title": "Saraswati Ji Kotadiya", "value": "saraswati_ji_kotadiya"},
  {"title": "Shikarchand Ji Bohra", "value": "shikarchand_ji_bohra"},
  {"title": "Shilpa Ji Gandhi", "value": "shilpa_ji_gandhi"},
  {"title": "Shweta Ji Bhandari", "value": "shweta_ji_bhandari"},
  {"title": "Sohan Ji Kathat", "value": "sohan_ji_kathat"},
  {"title": "Sonal Ji Merta", "value": "sonal_ji_merta"},
  {"title": "Sonali Ji Bafna", "value": "sonali_ji_bafna"},
  {"title": "Suman Ji Singhvi", "value": "suman_ji_singhvi"},
  {"title": "Sunanda Ji Jain", "value": "sunanda_ji_jain"},
  {"title": "Sundarlal Ji Salecha", "value": "sundarlal_ji_salecha"},
  {"title": "Sunita Ji Mehta", "value": "sunita_ji_mehta"},
  {"title": "Suraj Ji Bohra", "value": "suraj_ji_bohra"},
  {"title": "Suresh Ji Hingar", "value": "suresh_ji_hingar"},
  {"title": "Sushila Ji Gulecha", "value": "sushila_ji_gulecha"},
  {"title": "Sushma Ji Singhvi", "value": "sushma_ji_singhvi"},
  {"title": "Usha Ji Bhandari", "value": "usha_ji_bhandari"},
  {"title": "Usha Ji Bohra", "value": "usha_ji_bohra"},
  {"title": "Vaishali Ji Jain", "value": "vaishali_ji_jain"},
  {"title": "Vaishali Ji Kumbhat", "value": "vaishali_ji_kumbhat"},
  {"title": "Vinita Ji Mehta", "value": "vinita_ji_mehta"},
  {"title": "Vinod Ji Jain", "value": "vinod_ji_jain"}
];

const months = [
  {
    "title": "January",
    "value": "01",
  },
  {
    "title": "February",
    "value": "02",
  },
  {
    "title": "March",
    "value": "03",
  },
  {
    "title": "April",
    "value": "04",
  },
  {
    "title": "May",
    "value": "05",
  },
  {
    "title": "June",
    "value": "06",
  },
  {
    "title": "July",
    "value": "07",
  },
  {
    "title": "August",
    "value": "08",
  },
  {
    "title": "September",
    "value": "09",
  },
  {
    "title": "October",
    "value": "10",
  },
  {
    "title": "November",
    "value": "11",
  },
  {
    "title": "December",
    "value": "12",
  },
];
//////////////////////////////////////////////
const month = [
  {
    "title": "January",
    "value": "JAN",
  },
  {
    "title": "February",
    "value": "FEB",
  },
  {
    "title": "March",
    "value": "MAR",
  },
  {
    "title": "April",
    "value": "APR",
  },
  {
    "title": "May",
    "value": "MAY",
  },
  {
    "title": "June",
    "value": "JUN",
  },
  {
    "title": "July",
    "value": "JUL",
  },
  {
    "title": "August",
    "value": "AUG",
  },
  {
    "title": "September",
    "value": "SEP",
  },
  {
    "title": "October",
    "value": "OCT",
  },
  {
    "title": "November",
    "value": "NOV",
  },
  {
    "title": "December",
    "value": "DEC",
  },
];
////////////////////////////////////////////////////////
const year = [
  {
    "title": "2018",
    "value": "2018",
  },
  {
    "title": "2019",
    "value": "2019",
  },
  {
    "title": "2020",
    "value": "2020",
  },
  {
    "title": "2021",
    "value": "2021",
  },
  {
    "title": "2022",
    "value": "2022",
  },
  {
    "title": "2023",
    "value": "2023",
  },
  {
    "title": "2024",
    "value": "2024",
  },
  {
    "title": "2025",
    "value": "2025",
  }
];
////////////////////////////////
const postCities = [
  {"title": "Ahmedabad (Guj.)", "value": 0},
  {"title": "Aagoli (Raj.)", "value": 1},
  {"title": "Ajmer (Raj.)", "value": 2},
  {"title": "Alanpur (Raj.)", "value": 3},
  {"title": "Aligarh Rampura (Raj.)", "value": 4},
  {"title": "Alwar (Raj.)", "value": 5},
  {"title": "Artiya Kala (Raj.)", "value": 6},
  {"title": "Bajariya-SWM (Raj.)", "value": 7},
  {"title": "Balotara (Raj.)", "value": 8},
  {"title": "Bangaluru (K.T.)", "value": 9},
  {"title": "Bargama (Raj.)", "value": 10},
  {"title": "Baun (Raj.)", "value": 11},
  {"title": "Beawar (Raj.)", "value": 12},
  {"title": "Betul  (M.P.)", "value": 13},
  {"title": "Bharatpur (Raj.)", "value": 14},
  {"title": "Bhopal  (M.P.)", "value": 15},
  {"title": "Bhopalgarh (Raj.)", "value": 16},
  {"title": "Bichgawa (Raj.)", "value": 17},
  {"title": "Bijapur (K.T.)", "value": 18},
  {"title": "Bikaner (Raj.)", "value": 19},
  {"title": "Chauth Ka Barwara (Raj.)", "value": 20},
  {"title": "Chennai (T.N.)", "value": 21},
  {"title": "Dahra mod (Raj.)", "value": 22},
  {"title": "Dei (Raj.)", "value": 23},
  {"title": "Delhi", "value": 24},
  {"title": "Devli (Raj.)", "value": 25},
  {"title": "Dhanop (Raj.)", "value": 26},
  {"title": "Dudu (Raj.)", "value": 27},
  {"title": "Duni (Raj.)", "value": 28},
  {"title": "Gangapur City (Raj.)", "value": 29},
  {"title": "Gopalgarh-Bharatpur (Raj.)", "value": 30},
  {"title": "Gotan (Raj.)", "value": 31},
  {"title": "Harsana (Raj.)", "value": 32},
  {"title": "Hindaun City (Raj.)", "value": 33},
  {"title": "Holnantha (M.H.)", "value": 34},
  {"title": "Housing Board-SWM (Raj.)", "value": 35},
  {"title": "Hyderabad (A.P.)", "value": 36},
  {"title": "Ichalkaranji (K.T.)", "value": 37},
  {"title": "Indore (M.P.)", "value": 38},
  {"title": "Jabalpur  (M.P.)", "value": 39},
  {"title": "Jaipur (Raj.)", "value": 40},
  {"title": "Jalgaon (M.H.)", "value": 41},
  {"title": "Jarkhoda (Raj.)", "value": 42},
  {"title": "Jodhpur (Raj.)", "value": 43},
  {"title": "Kajgaon (M.H.)", "value": 44},
  {"title": "Kanpur (U.P.)", "value": 45},
  {"title": "Karauli (Raj.)", "value": 46},
  {"title": "Kathumar (Raj.)", "value": 47},
  {"title": "Kherli (Raj.)", "value": 48},
  {"title": "Khoh (Raj.)", "value": 49},
  {"title": "Kishangarh City (Raj.)", "value": 50},
  {"title": "Kolkata (P.B.)", "value": 51},
  {"title": "Kota", "value": 52},
  {"title": "Kundera (Raj.)", "value": 53},
  {"title": "Kushtala (Raj.)", "value": 54},
  {"title": "Lasur (M.H.)", "value": 55},
  {"title": "Madanganj (Raj.)", "value": 56},
  {"title": "Malpura (u.p.)", "value": 57},
  {"title": "Mandawar (Raj.)", "value": 58},
  {"title": "Maujpur (Raj.)", "value": 59},
  {"title": "Merta City (Raj.)", "value": 60},
  {"title": "Mumbai (M.H.)", "value": 61},
  {"title": "Mysore (K.T.)", "value": 62},
  {"title": "Nadbai (Raj.)", "value": 63},
  {"title": "Nagaur (Raj.)", "value": 64},
  {"title": "Nagpur (M.H.)", "value": 65},
  {"title": "Nasiya, Gangapur city (Raj.)", "value": 66},
  {"title": "Navsari (Guj.)", "value": 67},
  {"title": "Neemach  (M.P.)", "value": 68},
  {"title": "Pachala (Raj.)", "value": 69},
  {"title": "Paharsar (Raj.)", "value": 70},
  {"title": "Pahuna (Raj.)", "value": 71},
  {"title": "Palasani (Raj.)", "value": 72},
  {"title": "Pali (Raj.)", "value": 73},
  {"title": "Pipar City (Raj.)", "value": 74},
  {"title": "Raichur (K.T.)", "value": 75},
  {"title": "Rasidpur (Raj.)", "value": 76},
  {"title": "Satara (M.H.)", "value": 77},
  {"title": "Sawaimadhopur City (Raj.)", "value": 78},
  {"title": "Sewala (Raj.)", "value": 79},
  {"title": "Shorapur  (K.T.)", "value": 80},
  {"title": "Shyopur Kala  (M.P.)", "value": 81},
  {"title": "Sumerganj Mandi (Raj.)", "value": 82},
  {"title": "Surat (Guj.)", "value": 83},
  {"title": "Udaipur (Raj.)", "value": 84},
  {"title": "Vardhman Nagar, Hinduan (Raj.)", "value": 85},
  {"title": "Vigyan Nagar, Kota (Raj.)", "value": 86},
  // {"title": "Aawasan Mandal-Sawai Madhopur", "value": 0},
  // {"title": "Ahmedabad", "value": 1},
  // {"title": "Ajmer", "value": 2},
  // {"title": "Balotra", "value": 3},
  // {"title": "Bengaluru", "value": 4},
  // {"title": "Chennai", "value": 5},
  // {"title": "Hindon City", "value": 6},
  // {"title": "Jaipur", "va": 7},
  // {"title": "Jalgaon", "value": 8},
  // {"title": "Jodhpur", "value": 9},
  // {"title": "Kolkata", "value": 10},
  // {"title": "Kota", "value": 11},
  // {"title": "Mumbai", "value": 12},
  // {"title": "Nagpur", "value": 13},
  // {"title": "New Delhi", "value": 14},
  // {"title": "Nimach", "value": 15},
  // {"title": "Pali-Marwar", "value": 16},
  // {"title": "Pipar City", "value": 17},
  // {"title": "Sawai Madhopur", "value": 18},
  // {"title": "Secunderabad", "value": 19},
  // {"title": "Surat", "value": 20},
  // {"title": "Vardhman Nagar - Hindon City", "value": 21}
];
const area = [
  {"title": "Air Force Area", "value": 0},
  {"title": "Ashok Nagar", "value": 1},
  {"title": "Abhishek Nagar, Pal Gaon", "value": 2},
  {"title": "Ajit Colony", "value": 3},
  {"title": "Amrit Nagar", "value": 4},
  {"title": "Ajmer Line Military Quaters, Cantt Area", "value": 5},
  {"title": "BJS Colony", "value": 6},
  {"title": "Basni", "value": 7},
  {"title": "Balsamand, Mandore", "value": 8},
  {"title": "Bhadu Market", "value": 9},
  {"title": "Bhatti Ki Bawari, Chopasni Housing Board", "value": 10},
  {"title": "Bhagat Ki Kothi", "value": 11},
  {"title": "Basni, Boranada", "value": 12},
  {"title": "Bhatinda", "value": 13},
  {"title": "Baldev Nagar", "value": 14},
  {"title": "Bhistiyon Ka Bas", "value": 15},
  {"title": "Basni Phase 1, Basni", "value": 16},
  {"title": "Bhakrasni", "value": 17},
  {"title": "Chopasni Housing Board", "value": 18},
  {"title": "Cantt Area", "value": 19},
  {"title": "Chaukhan", "value": 20},
  {"title": "D-Kirtinagar, Rawat Nagar", "value": 21},
  {"title": "Digari Kalla", "value": 22},
  {"title": "East Patel Nagar", "value": 23},
  {"title": "Gopal Bari", "value": 24},
  {"title": "Gangana", "value": 25},
  {"title": "Gulab Sagar", "value": 26},
  {"title": "H I Area Phase 2, Basni", "value": 27},
  {"title": "Indira Colony, Pratap Nagar", "value": 28},
  {"title": "Jhalamand", "value": 29},
  {"title": "Jwala Vihar", "value": 30},
  {"title": "Kudi Bhagtasni Housing Board", "value": 31},
  {"title": "Kamla Nehru Nagar, 1st Pulia", "value": 32},
  {"title": "Khema-Ka-Kuwa", "value": 33},
  {"title": "Kabir Nagar", "value": 34},
  {"title": "Kamla Nehru Nagar 3, 1st Pulia", "value": 35},
  {"title": "Krishna Nagar", "value": 36},
  {"title": "Kanhaiya Nagar, Sirodi", "value": 37},
  {"title": "Laxmi Nagar", "value": 38},
  {"title": "Madhuban Colony", "value": 39},
  {"title": "Maha Mandir Area", "value": 40},
  {"title": "Mata Ka Than, Rawat Nagar", "value": 41},
  {"title": "Mandore", "value": 42},
  {"title": "Mansarover Colony", "value": 43},
  {"title": "MIA 2nd Phase, Basni", "value": 44},
  {"title": "M.I.A. 1st Phase, Basni, Basni", "value": 45},
  {"title": "Mahadev Nagar", "value": 46},
  {"title": "Meera Nagar", "value": 47},
  {"title": "Maderna", "value": 48},
  {"title": "New Roop Nagar", "value": 49},
  {"title": "Nandanvan Nagar, Chopasni Housing Board", "value": 50},
  {"title": "Nandri", "value": 51},
  {"title": "Nayapura", "value": 52},
  {"title": "Nayapura", "value": 53},
  {"title": "Nandara Kalan District", "value": 54},
  {"title": "Nagori Bera, Mandore", "value": 55},
  {"title": "Parsvnath City", "value": 56},
  {"title": "Paota", "value": 57},
  {"title": "Pal Gaon", "value": 58},
  {"title": "Pratap Nagar", "value": 59},
  {"title": "Prem Nagar", "value": 60},
  {"title": "Prithviraj Nagar", "value": 61},
  {"title": "Pal Balaji, Khema-Ka-Kuwa", "value": 62},
  {"title": "Pali District, Rajasthan", "value": 63},
  {"title": "Phase 1st, Sangriya", "value": 64},
  {"title": "P.W.D Colony", "value": 65},
  {"title": "Pabupura", "value": 66},
  {"title": "Paradise Villa", "value": 67},
  {"title": "Ratanada", "value": 68},
  {"title": "Rawat Nagar", "value": 69},
  {"title": "Rawaton Ka Bass", "value": 70},
  {"title": "Ravit", "value": 71},
  {"title": "Ramdev Nagar", "value": 72},
  {"title": "Rishikesh Nagar, Mandore", "value": 73},
  {"title": "Shastri Nagar", "value": 74},
  {"title": "Sardarpura", "value": 75},
  {"title": "Shikargarh Enclave", "value": 76},
  {"title": "Saran Nagar", "value": 77},
  {"title": "Subhash Chowk, Ratanada", "value": 78},
  {"title": "Saraswati Nagar, Basni", "value": 79},
  {"title": "Sector 19, Chopasni Housing Board", "value": 80},
  {"title": "Sector 14, Chopasni Housing Board", "value": 81},
  {"title": "Shyam Nagar", "value": 82},
  {"title": "Sector 1, Kudi Bhagtasni Housing Board", "value": 83},
  {"title": "Sector 7, Kudi Bhagtasni Housing Board", "value": 84},
  {"title": "Sector 3, Kudi Bhagtasni Housing Board", "value": 85},
  {"title": "Sector 15, Chopasni Housing Board", "value": 86},
  {"title": "Sangriya", "value": 87},
  {"title": "Subhash Nagar", "value": 88},
  {"title": "Sirodi", "value": 89},
  {"title": "Sector-E, Shastri Nagar", "value": 90},
  {"title": "Sector 5, Kudi Bhagtasni Housing Board", "value": 91},
  {"title": "Surya Colony", "value": 92},
  {"title": "Shri Ram Nagar, Rawat Nagar", "value": 93},
  {"title": "Sodagaran Mohalla", "value": 94},
  {"title": "Sector 23, Chopasni Housing Board", "value": 95},
  {"title": "Suraj Nagar, Gopal Bari", "value": 96},
  {"title": "Sector 21, Chopasni Housing Board", "value": 97},
  {"title": "Salawas District", "value": 98},
  {"title": "Sector-H, Shastri Nagar", "value": 99},
  {"title": "Shramikpura, Baldev Nagar", "value": 100},
  {"title": "Samrat Nagar, Sirodi", "value": 101},
  {"title": "Shiv Shakti Sector, Pratap Nagar", "value": 102},
  {"title": "Siriyade Gaon", "value": 103},
  {"title": "Tanawada", "value": 104},
  {"title": "Vivek Vihar", "value": 105},
  {"title": "Vidhya Nagar", "value": 106}
];

const state = [
  {"value": "0", "title": "Andaman and Nicobar Islands"},
  {"value": "1", "title": "Andhra Pradesh"},
  {"value": "2", "title": "Arunachal Pradesh"},
  {"value": "3", "title": "Assam"},
  {"value": "4", "title": "Bihar"},
  {"value": "5", "title": "Chandigarh"},
  {"value": "6", "title": "Chhattisgarh"},
  {"value": "7", "title": "Dadra and Nagar Haveli"},
  {"value": "8", "title": "Daman and Diu"},
  {"value": "9", "title": "Delhi"},
  {"value": "10", "title": "Goa"},
  {"value": "11", "title": "Gujarat"},
  {"value": "12", "title": "Haryana"},
  {"value": "13", "title": "Himachal Pradesh"},
  {"value": "14", "title": "Jammu and Kashmir"},
  {"value": "15", "title": "Jharkhand"},
  {"value": "16", "title": "Karnataka"},
  {"value": "17", "title": "Kerala"},
  {"value": "36", "title": "Ladakh"},
  {"value": "18", "title": "Lakshadweep"},
  {"value": "19", "title": "Madhya Pradesh"},
  {"value": "20", "title": "Maharashtra"},
  {"value": "21", "title": "Manipur"},
  {"value": "22", "title": "Meghalaya"},
  {"value": "23", "title": "Mizoram"},
  {"value": "24", "title": "Nagaland"},
  {"value": "25", "title": "Orissa"},
  {"value": "26", "title": "Puducherry"},
  {"value": "27", "title": "Punjab"},
  {"value": "28", "title": "Rajasthan"},
  {"value": "29", "title": "Sikkim"},
  {"value": "30", "title": "Tamil Nadu"},
  {"value": "31", "title": "Telangana"},
  {"value": "32", "title": "Tripura"},
  {"value": "33", "title": "Uttarakhand"},
  {"value": "34", "title": "Uttar Pradesh"},
  {"value": "35", "title": "West Bengal"}
];

const cities = [
  {
    "title": "Ajmer",
    "value": 0,
    "st": "28",
  },
  {
    "title": "Alwar",
    "value": 1,
    "st": "28",
  },
  {
    "title": "Banswara",
    "value": 2,
    "st": "28",
  },
  {
    "title": "Baran",
    "value": 3,
    "st": "28",
  },
  {
    "title": "Barmer",
    "value": 4,
    "st": "28",
  },
  {
    "title": "Bharatpur",
    "value": 5,
    "st": "28",
  },
  {
    "title": "Bhilwara",
    "value": 6,
    "st": "28",
  },
  {
    "title": "Bikaner",
    "value": 7,
    "st": "28",
  },
  {
    "title": "Bundi",
    "value": 8,
    "st": "28",
  },
  {
    "title": "Chittaurgarh",
    "value": 9,
    "st": "28",
  },
  {
    "title": "Churu",
    "value": 10,
    "st": "28",
  },
  {
    "title": "Dausa",
    "value": 11,
    "st": "28",
  },
  {
    "title": "Dholpur",
    "value": 12,
    "st": "28",
  },
  {
    "title": "Dungarpur",
    "value": 13,
    "st": "28",
  },
  {
    "title": "Hanumangarh",
    "value": 14,
    "st": "28",
  },
  {
    "title": "Jaipur",
    "value": 15,
    "st": "28",
  },
  {
    "title": "Jaisalmer",
    "value": 16,
    "st": "28",
  },
  {
    "title": "Jalor",
    "value": 17,
    "st": "28",
  },
  {
    "title": "Jhalawar",
    "value": 18,
    "st": "28",
  },
  {
    "title": "Jhunjhunu",
    "value": 19,
    "st": "28",
  },
  {
    "title": "Jodhpur",
    "value": 20,
    "st": "28",
  },
  {
    "title": "Karauli",
    "value": 21,
    "st": "28",
  },
  {
    "title": "Kota",
    "value": 22,
    "st": "28",
  },
  {
    "title": "Nagaur",
    "value": 23,
    "st": "28",
  },
  {
    "title": "Pali",
    "value": 24,
    "st": "28",
  },
  {
    "title": "Pratapgarh",
    "value": 25,
    "st": "28",
  },
  {
    "title": "Rajsamand",
    "value": 26,
    "st": "28",
  },
  {
    "title": "Sawai Madhopur",
    "value": 27,
    "st": "28",
  },
  {
    "title": "Sikar",
    "value": 28,
    "st": "28",
  },
  {
    "title": "Sirohi",
    "value": 29,
    "st": "28",
  },
  {
    "title": "Sri Ganganagar",
    "value": 30,
    "st": "28",
  },
  {
    "title": "Tonk",
    "value": 31,
    "st": "28",
  },
  {
    "title": "Udaipur",
    "value": 32,
    "st": "28",
  },
  {"st": "0", "title": "Nicobar", "value": 33},
  {"st": "0", "title": "North Middle Andaman", "value": 34},
  {"st": "0", "title": "South Andaman", "value": 35},
  {"st": "1", "title": "Anantapur", "value": 36},
  {"st": "1", "title": "Chittoor", "value": 37},
  {"st": "1", "title": "East Godavari", "value": 38},
  {"st": "1", "title": "Guntur", "value": 39},
  {"st": "1", "title": "Kadapa", "value": 40},
  {"st": "1", "title": "Krishna", "value": 41},
  {"st": "1", "title": "Kurnool", "value": 42},
  {"st": "1", "title": "Nellore", "value": 43},
  {"st": "1", "title": "Prakasam", "value": 44},
  {"st": "1", "title": "Srikakulam", "value": 45},
  {"st": "1", "title": "Visakhapatnam", "value": 46},
  {"st": "1", "title": "Vizianagaram", "value": 47},
  {"st": "1", "title": "West Godavari", "value": 48},
  {"st": "2", "title": "Anjaw", "value": 49},
  {"st": "2", "title": "Central Siang", "value": 50},
  {"st": "2", "title": "Changlang", "value": 51},
  {"st": "2", "title": "Dibang Valley", "value": 52},
  {"st": "2", "title": "East Kameng", "value": 53},
  {"st": "2", "title": "East Siang", "value": 54},
  {"st": "2", "title": "Kamle", "value": 55},
  {"st": "2", "title": "Kra Daadi", "value": 56},
  {"st": "2", "title": "Kurung Kumey", "value": 57},
  {"st": "2", "title": "Lepa Rada", "value": 58},
  {"st": "2", "title": "Lohit", "value": 59},
  {"st": "2", "title": "Longding", "value": 60},
  {"st": "2", "title": "Lower Dibang Valley", "value": 61},
  {"st": "2", "title": "Lower Siang", "value": 62},
  {"st": "2", "title": "Lower Subansiri", "value": 63},
  {"st": "2", "title": "Namsai", "value": 64},
  {"st": "2", "title": "Pakke Kessang", "value": 65},
  {"st": "2", "title": "Papum Pare", "value": 66},
  {"st": "2", "title": "Shi Yomi", "value": 67},
  {"st": "2", "title": "Tawang", "value": 68},
  {"st": "2", "title": "Tirap", "value": 69},
  {"st": "2", "title": "Upper Siang", "value": 70},
  {"st": "2", "title": "Upper Subansiri", "value": 71},
  {"st": "2", "title": "West Kameng", "value": 72},
  {"st": "2", "title": "West Siang", "value": 73},
  {"st": "3", "title": "Bajali", "value": 74},
  {"st": "3", "title": "Baksa", "value": 75},
  {"st": "3", "title": "Barpeta", "value": 76},
  {"st": "3", "title": "Biswanath", "value": 77},
  {"st": "3", "title": "Bongaigaon", "value": 78},
  {"st": "3", "title": "Cachar", "value": 79},
  {"st": "3", "title": "Charaideo", "value": 80},
  {"st": "3", "title": "Chirang", "value": 81},
  {"st": "3", "title": "Darrang", "value": 82},
  {"st": "3", "title": "Dhemaji", "value": 83},
  {"st": "3", "title": "Dhubri", "value": 84},
  {"st": "3", "title": "Dibrugarh", "value": 85},
  {"st": "3", "title": "Dima Hasao", "value": 86},
  {"st": "3", "title": "Goalpara", "value": 87},
  {"st": "3", "title": "Golaghat", "value": 88},
  {"st": "3", "title": "Hailakandi", "value": 89},
  {"st": "3", "title": "Hojai", "value": 90},
  {"st": "3", "title": "Jorhat", "value": 91},
  {"st": "3", "title": "Kamrup", "value": 92},
  {"st": "3", "title": "Kamrup Metropolitan", "value": 93},
  {"st": "3", "title": "Karbi Anglong", "value": 94},
  {"st": "3", "title": "Karimganj", "value": 95},
  {"st": "3", "title": "Kokrajhar", "value": 96},
  {"st": "3", "title": "Lakhimpur", "value": 97},
  {"st": "3", "title": "Majuli", "value": 98},
  {"st": "3", "title": "Morigaon", "value": 99},
  {"st": "3", "title": "Nagaon", "value": 100},
  {"st": "3", "title": "Nalbari", "value": 101},
  {"st": "3", "title": "Sivasagar", "value": 102},
  {"st": "3", "title": "Sonitpur", "value": 103},
  {"st": "3", "title": "South Salmara-Mankachar", "value": 104},
  {"st": "3", "title": "Tinsukia", "value": 105},
  {"st": "3", "title": "Udalguri", "value": 106},
  {"st": "3", "title": "West Karbi Anglong", "value": 107},
  {"st": "4", "title": "Araria", "value": 108},
  {"st": "4", "title": "Arwal", "value": 109},
  {"st": "4", "title": "Aurangabad", "value": 110},
  {"st": "4", "title": "Banka", "value": 111},
  {"st": "4", "title": "Begusarai", "value": 112},
  {"st": "4", "title": "Bhagalpur", "value": 113},
  {"st": "4", "title": "Bhojpur", "value": 114},
  {"st": "4", "title": "Buxar", "value": 115},
  {"st": "4", "title": "Darbhanga", "value": 116},
  {"st": "4", "title": "East Champaran", "value": 117},
  {"st": "4", "title": "Gaya", "value": 118},
  {"st": "4", "title": "Gopalganj", "value": 119},
  {"st": "4", "title": "Jamui", "value": 120},
  {"st": "4", "title": "Jehanabad", "value": 121},
  {"st": "4", "title": "Kaimur", "value": 122},
  {"st": "4", "title": "Katihar", "value": 123},
  {"st": "4", "title": "Khagaria", "value": 124},
  {"st": "4", "title": "Kishanganj", "value": 125},
  {"st": "4", "title": "Lakhisarai", "value": 126},
  {"st": "4", "title": "Madhepura", "value": 127},
  {"st": "4", "title": "Madhubani", "value": 128},
  {"st": "4", "title": "Munger", "value": 129},
  {"st": "4", "title": "Muzaffarpur", "value": 130},
  {"st": "4", "title": "Nalanda", "value": 131},
  {"st": "4", "title": "Nawada", "value": 132},
  {"st": "4", "title": "Patna", "value": 133},
  {"st": "4", "title": "Purnia", "value": 134},
  {"st": "4", "title": "Rohtas", "value": 135},
  {"st": "4", "title": "Saharsa", "value": 136},
  {"st": "4", "title": "Samastipur", "value": 137},
  {"st": "4", "title": "Saran", "value": 138},
  {"st": "4", "title": "Sheikhpura", "value": 139},
  {"st": "4", "title": "Sheohar", "value": 140},
  {"st": "4", "title": "Sitamarhi", "value": 141},
  {"st": "4", "title": "Siwan", "value": 142},
  {"st": "4", "title": "Supaul", "value": 143},
  {"st": "4", "title": "Vaishali", "value": 144},
  {"st": "4", "title": "West Champaran", "value": 145},
  {"st": "5", "title": "Chandigarh", "value": 146},
  {
    "st": "6",
    "title": "Balod",
    "value": 147,
  },
  {
    "st": "6",
    "title": "Baloda Bazar",
    "value": 148,
  },
  {
    "st": "6",
    "title": "Balrampur",
    "value": 149,
  },
  {
    "st": "6",
    "title": "Bastar",
    "value": 150,
  },
  {
    "st": "6",
    "title": "Bemetara",
    "value": 151,
  },
  {
    "st": "6",
    "title": "Bijapur",
    "value": 152,
  },
  {
    "st": "6",
    "title": "Bilaspur",
    "value": 153,
  },
  {
    "st": "6",
    "title": "Dantewada",
    "value": 154,
  },
  {
    "st": "6",
    "title": "Dhamtari",
    "value": 155,
  },
  {
    "st": "6",
    "title": "Durg",
    "value": 156,
  },
  {
    "st": "6",
    "title": "Gariaband",
    "value": 157,
  },
  {
    "st": "6",
    "title": "Gaurela Pendra Marwahi",
    "value": 158,
  },
  {
    "st": "6",
    "title": "Janjgir Champa",
    "value": 159,
  },
  {
    "st": "6",
    "title": "Jashpur",
    "value": 160,
  },
  {
    "st": "6",
    "title": "Kabirdham",
    "value": 161,
  },
  {
    "st": "6",
    "title": "Kanker",
    "value": 162,
  },
  {
    "st": "6",
    "title": "Kondagaon",
    "value": 163,
  },
  {
    "st": "6",
    "title": "Korba",
    "value": 164,
  },
  {
    "st": "6",
    "title": "Koriya",
    "value": 165,
  },
  {
    "st": "6",
    "title": "Mahasamund",
    "value": 166,
  },
  {
    "st": "6",
    "title": "Mungeli",
    "value": 167,
  },
  {
    "st": "6",
    "title": "Narayanpur",
    "value": 168,
  },
  {
    "st": "6",
    "title": "Raigarh",
    "value": 169,
  },
  {
    "st": "6",
    "title": "Raipur",
    "value": 170,
  },
  {
    "st": "6",
    "title": "Rajnandgaon",
    "value": 171,
  },
  {
    "st": "6",
    "title": "Sukma",
    "value": 172,
  },
  {
    "st": "6",
    "title": "Surajpur",
    "value": 173,
  },
  {
    "st": "6",
    "title": "Surguja",
    "value": 174,
  },
  {"st": "7", "title": "Dadra Nagar Haveli", "value": 175},
  {"st": "8", "title": "Daman", "value": 176},
  {"st": "8", "title": "Diu", "value": 177},
  {"st": "9", "title": "Central Delhi", "value": 178},
  {"st": "9", "title": "East Delhi", "value": 179},
  {"st": "9", "title": "New Delhi", "value": 180},
  {"st": "9", "title": "North Delhi", "value": 181},
  {"st": "9", "title": "North East Delhi", "value": 182},
  {"st": "9", "title": "North West Delhi", "value": 183},
  {"st": "9", "title": "Shahdara", "value": 184},
  {"st": "9", "title": "South Delhi", "value": 185},
  {"st": "9", "title": "South East Delhi", "value": 186},
  {"st": "9", "title": "South West Delhi", "value": 187},
  {"st": "9", "title": "West Delhi", "value": 188},
  {"st": "10", "title": "North Goa", "value": 189},
  {"st": "10", "title": "South Goa", "value": 190},
  {"st": "11", "title": "Ahmedabad", "value": 191},
  {"st": "11", "title": "Amreli", "value": 192},
  {"st": "11", "title": "Anand", "value": 193},
  {"st": "11", "title": "Aravalli", "value": 194},
  {"st": "11", "title": "Banaskantha", "value": 195},
  {"st": "11", "title": "Bharuch", "value": 196},
  {"st": "11", "title": "Bhavnagar", "value": 197},
  {"st": "11", "title": "Botad", "value": 198},
  {"st": "11", "title": "Chhota Udaipur", "value": 199},
  {"st": "11", "title": "Dahod", "value": 200},
  {"st": "11", "title": "Dang", "value": 201},
  {"st": "11", "title": "Devbhoomi Dwarka", "value": 202},
  {"st": "11", "title": "Gandhinagar", "value": 203},
  {"st": "11", "title": "Gir Somnath", "value": 204},
  {"st": "11", "title": "Jamnagar", "value": 205},
  {"st": "11", "title": "Junagadh", "value": 206},
  {"st": "11", "title": "Kheda", "value": 207},
  {"st": "11", "title": "Kutch", "value": 208},
  {"st": "11", "title": "Mahisagar", "value": 209},
  {"st": "11", "title": "Mehsana", "value": 210},
  {"st": "11", "title": "Morbi", "value": 211},
  {"st": "11", "title": "Narmada", "value": 212},
  {"st": "11", "title": "Navsari", "value": 213},
  {"st": "11", "title": "Panchmahal", "value": 214},
  {"st": "11", "title": "Patan", "value": 215},
  {"st": "11", "title": "Porbandar", "value": 216},
  {"st": "11", "title": "Rajkot", "value": 217},
  {"st": "11", "title": "Sabarkantha", "value": 218},
  {"st": "11", "title": "Surat", "value": 219},
  {"st": "11", "title": "Surendranagar", "value": 220},
  {"st": "11", "title": "Tapi", "value": 221},
  {"st": "11", "title": "Vadodara", "value": 222},
  {"st": "11", "title": "Valsad", "value": 223},
  {"st": "12", "title": "Ambala", "value": 224},
  {"st": "12", "title": "Bhiwani", "value": 225},
  {"st": "12", "title": "Charkhi Dadri", "value": 226},
  {"st": "12", "title": "Faridabad", "value": 227},
  {"st": "12", "title": "Fatehabad", "value": 228},
  {"st": "12", "title": "Gurugram", "value": 229},
  {"st": "12", "title": "Hisar", "value": 230},
  {"st": "12", "title": "Jhajjar", "value": 231},
  {"st": "12", "title": "Jind", "value": 232},
  {"st": "12", "title": "Kaithal", "value": 233},
  {"st": "12", "title": "Karnal", "value": 234},
  {"st": "12", "title": "Kurukshetra", "value": 235},
  {"st": "12", "title": "Mahendragarh", "value": 236},
  {"st": "12", "title": "Mewat", "value": 237},
  {"st": "12", "title": "Palwal", "value": 238},
  {"st": "12", "title": "Panchkula", "value": 239},
  {"st": "12", "title": "Panipat", "value": 240},
  {"st": "12", "title": "Rewari", "value": 241},
  {"st": "12", "title": "Rohtak", "value": 242},
  {"st": "12", "title": "Sirsa", "value": 243},
  {"st": "12", "title": "Sonipat", "value": 244},
  {"st": "12", "title": "Yamunanagar", "value": 245},
  {"st": "13", "value": 246, "title": "Bilaspur"},
  {"st": "13", "value": 247, "title": "Chamba"},
  {"st": "13", "value": 248, "title": "Hamirpur"},
  {"st": "13", "value": 249, "title": "Kangra"},
  {"st": "13", "value": 250, "title": "Kinnaur"},
  {"st": "13", "value": 251, "title": "Kullu"},
  {"st": "13", "value": 252, "title": "Lahaul Spiti"},
  {"st": "13", "value": 253, "title": "Mandi"},
  {"st": "13", "value": 254, "title": "Shimla"},
  {"st": "13", "value": 255, "title": "Sirmaur"},
  {"st": "13", "value": 256, "title": "Solan"},
  {"st": "13", "value": 257, "title": "Una"},
  {"st": "14", "value": 258, "title": "Anantnag"},
  {"st": "14", "value": 259, "title": "Bandipora"},
  {"st": "14", "value": 260, "title": "Baramulla"},
  {"st": "14", "value": 261, "title": "Budgam"},
  {"st": "14", "value": 262, "title": "Doda"},
  {"st": "14", "value": 263, "title": "Ganderbal"},
  {"st": "14", "value": 264, "title": "Jammu"},
  {"st": "14", "value": 265, "title": "Kathua"},
  {"st": "14", "value": 266, "title": "Kishtwar"},
  {"st": "14", "value": 267, "title": "Kulgam"},
  {"st": "14", "value": 268, "title": "Kupwara"},
  {"st": "14", "value": 269, "title": "Poonch"},
  {"st": "14", "value": 270, "title": "Pulwama"},
  {"st": "14", "value": 271, "title": "Rajouri"},
  {"st": "14", "value": 272, "title": "Ramban"},
  {"st": "14", "value": 273, "title": "Reasi"},
  {"st": "14", "value": 274, "title": "Samba"},
  {"st": "14", "value": 275, "title": "Shopian"},
  {"st": "14", "value": 276, "title": "Srinagar"},
  {"st": "14", "value": 277, "title": "Udhampur"},
  {"st": "15", "value": 278, "title": "Bokaro"},
  {"st": "15", "value": 279, "title": "Chatra"},
  {"st": "15", "value": 280, "title": "Deoghar"},
  {"st": "15", "value": 281, "title": "Dhanbad"},
  {"st": "15", "value": 282, "title": "Dumka"},
  {"st": "15", "value": 283, "title": "East Singhbhum"},
  {"st": "15", "value": 284, "title": "Garhwa"},
  {"st": "15", "value": 285, "title": "Giridih"},
  {"st": "15", "value": 286, "title": "Godda"},
  {"st": "15", "value": 287, "title": "Gumla"},
  {"st": "15", "value": 288, "title": "Hazaribagh"},
  {"st": "15", "value": 289, "title": "Jamtara"},
  {"st": "15", "value": 290, "title": "Khunti"},
  {"st": "15", "value": 291, "title": "Koderma"},
  {"st": "15", "value": 292, "title": "Latehar"},
  {"st": "15", "value": 293, "title": "Lohardaga"},
  {"st": "15", "value": 294, "title": "Pakur"},
  {"st": "15", "value": 295, "title": "Palamu"},
  {"st": "15", "value": 296, "title": "Ramgarh"},
  {"st": "15", "value": 297, "title": "Ranchi"},
  {"st": "15", "value": 298, "title": "Sahebganj"},
  {"st": "15", "value": 299, "title": "Seraikela Kharsawan"},
  {"st": "15", "value": 300, "title": "Simdega"},
  {"st": "15", "value": 301, "title": "West Singhbhum"},
  {"st": "16", "value": 302, "title": "Bagalkot"},
  {"st": "16", "value": 303, "title": "Bangalore Rural"},
  {"st": "16", "value": 304, "title": "Bangalore Urban"},
  {"st": "16", "value": 305, "title": "Belgaum"},
  {"st": "16", "value": 306, "title": "Bellary"},
  {"st": "16", "value": 307, "title": "Bidar"},
  {"st": "16", "value": 308, "title": "Chamarajanagar"},
  {"st": "16", "value": 309, "title": "Chikkaballapur"},
  {"st": "16", "value": 310, "title": "Chikkamagaluru"},
  {"st": "16", "value": 311, "title": "Chitradurga"},
  {"st": "16", "value": 312, "title": "Dakshina Kannada"},
  {"st": "16", "value": 313, "title": "Davanagere"},
  {"st": "16", "value": 314, "title": "Dharwad"},
  {"st": "16", "value": 315, "title": "Gadag"},
  {"st": "16", "value": 316, "title": "Gulbarga"},
  {"st": "16", "value": 317, "title": "Hassan"},
  {"st": "16", "value": 318, "title": "Haveri"},
  {"st": "16", "value": 319, "title": "Kodagu"},
  {"st": "16", "value": 320, "title": "Kolar"},
  {"st": "16", "value": 321, "title": "Koppal"},
  {"st": "16", "value": 322, "title": "Mandya"},
  {"st": "16", "value": 323, "title": "Mysore"},
  {"st": "16", "value": 324, "title": "Raichur"},
  {"st": "16", "value": 325, "title": "Ramanagara"},
  {"st": "16", "value": 326, "title": "Shimoga"},
  {"st": "16", "value": 327, "title": "Tumkur"},
  {"st": "16", "value": 328, "title": "Udupi"},
  {"st": "16", "value": 329, "title": "Uttara Kannada"},
  {"st": "16", "value": 330, "title": "Vijayanagara"},
  {"st": "16", "value": 331, "title": "Vijayapura"},
  {"st": "16", "value": 332, "title": "Yadgir"},
  {"st": "17", "value": 333, "title": "Alappuzha"},
  {"st": "17", "value": 334, "title": "Ernakulam"},
  {"st": "17", "value": 335, "title": "Idukki"},
  {"st": "17", "value": 336, "title": "Kannur"},
  {"st": "17", "value": 337, "title": "Kasaragod"},
  {"st": "17", "value": 338, "title": "Kollam"},
  {"st": "17", "value": 339, "title": "Kottayam"},
  {"st": "17", "value": 340, "title": "Kozhikode"},
  {"st": "17", "value": 341, "title": "Malappuram"},
  {"st": "17", "value": 342, "title": "Palakkad"},
  {"st": "17", "value": 343, "title": "Pathanamthitta"},
  {"st": "17", "value": 344, "title": "Thiruvananthapuram"},
  {"st": "17", "value": 345, "title": "Thrissur"},
  {"st": "17", "value": 346, "title": "Wayanad"},
  {"st": "36", "value": 347, "title": "Kargil"},
  {"st": "36", "value": 348, "title": "Leh"},
  {"st": "18", "value": 349, "title": "Lakshadweep"},
  {"st": "19", "title": "Agar Malwa", "value": 350},
  {"st": "19", "title": "Alirajpur", "value": 351},
  {"st": "19", "title": "Anuppur", "value": 352},
  {"st": "19", "title": "Ashoknagar", "value": 353},
  {"st": "19", "title": "Balaghat", "value": 354},
  {"st": "19", "title": "Barwani", "value": 355},
  {"st": "19", "title": "Betul", "value": 356},
  {"st": "19", "title": "Bhind", "value": 357},
  {"st": "19", "title": "Bhopal", "value": 358},
  {"st": "19", "title": "Burhanpur", "value": 359},
  {"st": "19", "title": "Chachaura", "value": 360},
  {"st": "19", "title": "Chhatarpur", "value": 361},
  {"st": "19", "title": "Chhindwara", "value": 362},
  {"st": "19", "title": "Damoh", "value": 363},
  {"st": "19", "title": "Datia", "value": 364},
  {"st": "19", "title": "Dewas", "value": 365},
  {"st": "19", "title": "Dhar", "value": 366},
  {"st": "19", "title": "Dindori", "value": 367},
  {"st": "19", "title": "Guna", "value": 368},
  {"st": "19", "title": "Gwalior", "value": 369},
  {"st": "19", "title": "Harda", "value": 370},
  {"st": "19", "title": "Hoshangabad", "value": 371},
  {"st": "19", "title": "Indore", "value": 372},
  {"st": "19", "title": "Jabalpur", "value": 373},
  {"st": "19", "title": "Jhabua", "value": 374},
  {"st": "19", "title": "Katni", "value": 375},
  {"st": "19", "title": "Khandwa", "value": 376},
  {"st": "19", "title": "Khargone", "value": 377},
  {"st": "19", "title": "Maihar", "value": 378},
  {"st": "19", "title": "Mandla", "value": 379},
  {"st": "19", "title": "Mandsaur", "value": 380},
  {"st": "19", "title": "Morena", "value": 381},
  {"st": "19", "title": "Nagda", "value": 382},
  {"st": "19", "title": "Narsinghpur", "value": 383},
  {"st": "19", "title": "Neemuch", "value": 384},
  {"st": "19", "title": "Niwari", "value": 385},
  {"st": "19", "title": "Panna", "value": 386},
  {"st": "19", "title": "Raisen", "value": 387},
  {"st": "19", "title": "Rajgarh", "value": 388},
  {"st": "19", "title": "Ratlam", "value": 389},
  {"st": "19", "title": "Rewa", "value": 390},
  {"st": "19", "title": "Sagar", "value": 391},
  {"st": "19", "title": "Satna", "value": 392},
  {"st": "19", "title": "Sehore", "value": 393},
  {"st": "19", "title": "Seoni", "value": 394},
  {"st": "19", "title": "Shahdol", "value": 395},
  {"st": "19", "title": "Shajapur", "value": 396},
  {"st": "19", "title": "Sheopur", "value": 397},
  {"st": "19", "title": "Shivpuri", "value": 398},
  {"st": "19", "title": "Sidhi", "value": 399},
  {"st": "19", "title": "Singrauli", "value": 400},
  {"st": "19", "title": "Tikamgarh", "value": 401},
  {"st": "19", "title": "Ujjain", "value": 402},
  {"st": "19", "title": "Umaria", "value": 403},
  {"st": "19", "title": "Vidisha", "value": 404},
  {"st": "20", "title": "Ahmednagar", "value": 405},
  {"st": "20", "title": "Akola", "value": 406},
  {"st": "20", "title": "Amravati", "value": 407},
  {"st": "20", "title": "Aurangabad", "value": 408},
  {"st": "20", "title": "Beed", "value": 409},
  {"st": "20", "title": "Bhandara", "value": 410},
  {"st": "20", "title": "Buldhana", "value": 411},
  {"st": "20", "title": "Chandrapur", "value": 412},
  {"st": "20", "title": "Dhule", "value": 413},
  {"st": "20", "title": "Gadchiroli", "value": 414},
  {"st": "20", "title": "Gondia", "value": 415},
  {"st": "20", "title": "Hingoli", "value": 416},
  {"st": "20", "title": "Jalgaon", "value": 417},
  {"st": "20", "title": "Jalna", "value": 418},
  {"st": "20", "title": "Kolhapur", "value": 419},
  {"st": "20", "title": "Latur", "value": 420},
  {"st": "20", "title": "Mumbai City", "value": 421},
  {"st": "20", "title": "Mumbai Suburban", "value": 422},
  {"st": "20", "title": "Nagpur", "value": 423},
  {"st": "20", "title": "Nanded", "value": 424},
  {"st": "20", "title": "Nandurbar", "value": 425},
  {"st": "20", "title": "Nashik", "value": 426},
  {"st": "20", "title": "Osmanabad", "value": 427},
  {"st": "20", "title": "Palghar", "value": 428},
  {"st": "20", "title": "Parbhani", "value": 429},
  {"st": "20", "title": "Pune", "value": 430},
  {"st": "20", "title": "Raigad", "value": 431},
  {"st": "20", "title": "Ratnagiri", "value": 432},
  {"st": "20", "title": "Sangli", "value": 433},
  {"st": "20", "title": "Satara", "value": 434},
  {"st": "20", "title": "Sindhudurg", "value": 435},
  {"st": "20", "title": "Solapur", "value": 436},
  {"st": "20", "title": "Thane", "value": 437},
  {"st": "20", "title": "Wardha", "value": 438},
  {"st": "20", "title": "Washim", "value": 439},
  {"st": "20", "title": "Yavatmal", "value": 440},
  {"st": "21", "title": "Bishnupur", "value": 441},
  {"st": "21", "title": "Chandel", "value": 442},
  {"st": "21", "title": "Churachandpur", "value": 443},
  {"st": "21", "title": "Imphal East", "value": 444},
  {"st": "21", "title": "Imphal West", "value": 445},
  {"st": "21", "title": "Jiribam", "value": 446},
  {"st": "21", "title": "Kakching", "value": 447},
  {"st": "21", "title": "Kamjong", "value": 448},
  {"st": "21", "title": "Kangpokpi", "value": 449},
  {"st": "21", "title": "Noney", "value": 450},
  {"st": "21", "title": "Pherzawl", "value": 451},
  {"st": "21", "title": "Senapati", "value": 452},
  {"st": "21", "title": "Tamenglong", "value": 453},
  {"st": "21", "title": "Tengnoupal", "value": 454},
  {"st": "21", "title": "Thoubal", "value": 455},
  {"st": "21", "title": "Ukhrul", "value": 456},
  {"st": "22", "value": 457, "title": "East Garo Hills"},
  {"st": "22", "value": 458, "title": "East Jaintia Hills"},
  {"st": "22", "value": 459, "title": "East Khasi Hills"},
  {"st": "22", "value": 460, "title": "North Garo Hills"},
  {"st": "22", "value": 461, "title": "Ri Bhoi"},
  {"st": "22", "value": 462, "title": "South Garo Hills"},
  {"st": "22", "value": 463, "title": "South West Garo Hills"},
  {"st": "22", "value": 464, "title": "South West Khasi Hills"},
  {"st": "22", "value": 465, "title": "West Garo Hills"},
  {"st": "22", "value": 466, "title": "West Jaintia Hills"},
  {"st": "22", "value": 467, "title": "West Khasi Hills"},
  {"st": "23", "value": 468, "title": "Aizawl"},
  {"st": "23", "value": 469, "title": "Champhai"},
  {"st": "23", "value": 470, "title": "Hnahthial"},
  {"st": "23", "value": 471, "title": "Kolasib"},
  {"st": "23", "value": 472, "title": "Khawzawl"},
  {"st": "23", "value": 473, "title": "Lawngtlai"},
  {"st": "23", "value": 474, "title": "Lunglei"},
  {"st": "23", "value": 475, "title": "Mamit"},
  {"st": "23", "value": 476, "title": "Saiha"},
  {"st": "23", "value": 477, "title": "Serchhip"},
  {"st": "23", "value": 478, "title": "Saitual"},
  {"st": "24", "value": 479, "title": "Dimapur"},
  {"st": "24", "value": 480, "title": "Kiphire"},
  {"st": "24", "value": 481, "title": "Kohima"},
  {"st": "24", "value": 482, "title": "Longleng"},
  {"st": "24", "value": 483, "title": "Mokokchung"},
  {"st": "24", "value": 484, "title": "Mon"},
  {"st": "24", "value": 485, "title": "Noklak"},
  {"st": "24", "value": 486, "title": "Peren"},
  {"st": "24", "value": 487, "title": "Phek"},
  {"st": "24", "value": 488, "title": "Tuensang"},
  {"st": "24", "value": 489, "title": "Wokha"},
  {"st": "24", "value": 490, "title": "Zunheboto"},
  {"st": "25", "value": 491, "title": "Angul"},
  {"st": "25", "value": 492, "title": "Balangir"},
  {"st": "25", "value": 493, "title": "Balasore"},
  {"st": "25", "value": 494, "title": "Bargarh"},
  {"st": "25", "value": 495, "title": "Bhadrak"},
  {"st": "25", "value": 496, "title": "Boudh"},
  {"st": "25", "value": 497, "title": "Cuttack"},
  {"st": "25", "value": 498, "title": "Debagarh"},
  {"st": "25", "value": 499, "title": "Dhenkanal"},
  {"st": "25", "value": 500, "title": "Gajapati"},
  {"st": "25", "value": 501, "title": "Ganjam"},
  {"st": "25", "value": 502, "title": "Jagatsinghpur"},
  {"st": "25", "value": 503, "title": "Jajpur"},
  {"st": "25", "value": 504, "title": "Jharsuguda"},
  {"st": "25", "value": 505, "title": "Kalahandi"},
  {"st": "25", "value": 506, "title": "Kandhamal"},
  {"st": "25", "value": 507, "title": "Kendrapara"},
  {"st": "25", "value": 508, "title": "Kendujhar"},
  {"st": "25", "value": 509, "title": "Khordha"},
  {"st": "25", "value": 510, "title": "Koraput"},
  {"st": "25", "value": 511, "title": "Malkangiri"},
  {"st": "25", "value": 512, "title": "Mayurbhanj"},
  {"st": "25", "value": 513, "title": "Nabarangpur"},
  {"st": "25", "value": 514, "title": "Nayagarh"},
  {"st": "25", "value": 515, "title": "Nuapada"},
  {"st": "25", "value": 516, "title": "Puri"},
  {"st": "25", "value": 517, "title": "Rayagada"},
  {"st": "25", "value": 518, "title": "Sambalpur"},
  {"st": "25", "value": 519, "title": "Subarnapur"},
  {"st": "25", "value": 520, "title": "Sundergarh"},
  {"st": "26", "value": 521, "title": "Karaikal"},
  {"st": "26", "value": 522, "title": "Mahe"},
  {"st": "26", "value": 523, "title": "Puducherry"},
  {"st": "26", "value": 524, "title": "Yanam"},
  {"st": "27", "value": 525, "title": "Amritsar"},
  {"st": "27", "value": 526, "title": "Barnala"},
  {"st": "27", "value": 527, "title": "Bathinda"},
  {"st": "27", "value": 528, "title": "Faridkot"},
  {"st": "27", "value": 529, "title": "Fatehgarh Sahib"},
  {"st": "27", "value": 530, "title": "Fazilka"},
  {"st": "27", "value": 531, "title": "Firozpur"},
  {"st": "27", "value": 532, "title": "Gurdaspur"},
  {"st": "27", "value": 533, "title": "Hoshiarpur"},
  {"st": "27", "value": 534, "title": "Jalandhar"},
  {"st": "27", "value": 535, "title": "Kapurthala"},
  {"st": "27", "value": 536, "title": "Ludhiana"},
  {"st": "27", "value": 537, "title": "Mansa"},
  {"st": "27", "value": 538, "title": "Moga"},
  {"st": "27", "value": 539, "title": "Mohali"},
  {"st": "27", "value": 540, "title": "Muktsar"},
  {"st": "27", "value": 541, "title": "Pathankot"},
  {"st": "27", "value": 542, "title": "Patiala"},
  {"st": "27", "value": 543, "title": "Rupnagar"},
  {"st": "27", "value": 544, "title": "Sangrur"},
  {"st": "27", "value": 545, "title": "Shaheed Bhagat Singh Nagar"},
  {"st": "27", "value": 546, "title": "Tarn Taran"},
  {"st": "29", "value": 547, "title": "East Sikkim"},
  {"st": "29", "value": 548, "title": "North Sikkim"},
  {"st": "29", "value": 549, "title": "South Sikkim"},
  {"st": "29", "value": 550, "title": "West Sikkim"},
  {"st": "30", "title": "Ariyalur", "value": 551},
  {"st": "30", "title": "Chengalpattu", "value": 552},
  {"st": "30", "title": "Chennai", "value": 553},
  {"st": "30", "title": "Coimbatore", "value": 554},
  {"st": "30", "title": "Cuddalore", "value": 555},
  {"st": "30", "title": "Dharmapuri", "value": 556},
  {"st": "30", "title": "Dindigul", "value": 557},
  {"st": "30", "title": "Erode", "value": 558},
  {"st": "30", "title": "Kallakurichi", "value": 559},
  {"st": "30", "title": "Kanchipuram", "value": 560},
  {"st": "30", "title": "Kanyakumari", "value": 561},
  {"st": "30", "title": "Karur", "value": 562},
  {"st": "30", "title": "Krishnagiri", "value": 562},
  {"st": "30", "title": "Madurai", "value": 563},
  {"st": "30", "title": "Mayiladuthurai", "value": 564},
  {"st": "30", "title": "Nagapattinam", "value": 565},
  {"st": "30", "title": "Namakkal", "value": 566},
  {"st": "30", "title": "Nilgiris", "value": 567},
  {"st": "30", "title": "Perambalur", "value": 568},
  {"st": "30", "title": "Pudukkottai", "value": 569},
  {"st": "30", "title": "Ramanathapuram", "value": 570},
  {"st": "30", "title": "Ranipet", "value": 571},
  {"st": "30", "title": "Salem", "value": 572},
  {"st": "30", "title": "Sivaganga", "value": 573},
  {"st": "30", "title": "Tenkasi", "value": 574},
  {"st": "30", "title": "Thanjavur", "value": 575},
  {"st": "30", "title": "Theni", "value": 576},
  {"st": "30", "title": "Thoothukudi", "value": 577},
  {"st": "30", "title": "Tiruchirappalli", "value": 578},
  {"st": "30", "title": "Tirunelveli", "value": 579},
  {"st": "30", "title": "Tirupattur", "value": 580},
  {"st": "30", "title": "Tiruppur", "value": 581},
  {"st": "30", "title": "Tiruvallur", "value": 582},
  {"st": "30", "title": "Tiruvannamalai", "value": 583},
  {"st": "30", "title": "Tiruvarur", "value": 584},
  {"st": "30", "title": "Vellore", "value": 585},
  {"st": "30", "title": "Viluppuram", "value": 586},
  {"st": "30", "title": "Virudhunagar", "value": 587},
  {"st": "31", "title": "Adilabad", "value": 588},
  {"st": "31", "title": "Bhadradri Kothagudem", "value": 589},
  {"st": "31", "title": "Hyderabad", "value": 590},
  {"st": "31", "title": "Jagtial", "value": 591},
  {"st": "31", "title": "Jangaon", "value": 592},
  {"st": "31", "title": "Jayashankar", "value": 593},
  {"st": "31", "title": "Jogulamba", "value": 594},
  {"st": "31", "title": "Kamareddy", "value": 595},
  {"st": "31", "title": "Karimnagar", "value": 596},
  {"st": "31", "title": "Khammam", "value": 597},
  {"st": "31", "title": "Komaram Bheem", "value": 598},
  {"st": "31", "title": "Mahabubabad", "value": 599},
  {"st": "31", "title": "Mahbubnagar", "value": 600},
  {"st": "31", "title": "Mancherial", "value": 601},
  {"st": "31", "title": "Medak", "value": 602},
  {"st": "31", "title": "Medchal", "value": 603},
  {"st": "31", "title": "Mulugu", "value": 604},
  {"st": "31", "title": "Nagarkurnool", "value": 605},
  {"st": "31", "title": "Nalgonda", "value": 606},
  {"st": "31", "title": "Narayanpet", "value": 607},
  {"st": "31", "title": "Nirmal", "value": 608},
  {"st": "31", "title": "Nizamabad", "value": 609},
  {"st": "31", "title": "Peddapalli", "value": 610},
  {"st": "31", "title": "Rajanna Sircilla", "value": 611},
  {"st": "31", "title": "Ranga Reddy", "value": 612},
  {"st": "31", "title": "Sangareddy", "value": 613},
  {"st": "31", "title": "Siddipet", "value": 614},
  {"st": "31", "title": "Suryapet", "value": 615},
  {"st": "31", "title": "Vikarabad", "value": 616},
  {"st": "31", "title": "Wanaparthy", "value": 617},
  {"st": "31", "title": "Warangal Rural", "value": 618},
  {"st": "31", "title": "Warangal Urban", "value": 619},
  {"st": "31", "title": "Yadadri Bhuvanagiri", "value": 620},
  {"st": "32", "value": 621, "title": "Dhalai"},
  {"st": "32", "value": 622, "title": "Gomati"},
  {"st": "32", "value": 623, "title": "Khowai"},
  {"st": "32", "value": 624, "title": "North Tripura"},
  {"st": "32", "value": 625, "title": "Sepahijala"},
  {"st": "32", "value": 626, "title": "South Tripura"},
  {"st": "32", "value": 627, "title": "Unakoti"},
  {"st": "32", "value": 628, "title": "West Tripura"},
  {"st": "33", "title": "Almora", "value": 629},
  {"st": "33", "title": "Bageshwar", "value": 630},
  {"st": "33", "title": "Chamoli", "value": 631},
  {"st": "33", "title": "Champawat", "value": 632},
  {"st": "33", "title": "Dehradun", "value": 633},
  {"st": "33", "title": "Haridwar", "value": 634},
  {"st": "33", "title": "Nainital", "value": 635},
  {"st": "33", "title": "Pauri", "value": 636},
  {"st": "33", "title": "Pithoragarh", "value": 637},
  {"st": "33", "title": "Rudraprayag", "value": 638},
  {"st": "33", "title": "Tehri", "value": 639},
  {"st": "33", "title": "Udham Singh Nagar", "value": 640},
  {"st": "33", "title": "Uttarkashi", "value": 641},
  {"st": "34", "value": 642, "title": "Agra"},
  {"st": "34", "value": 643, "title": "Aligarh"},
  {"st": "34", "value": 644, "title": "Ambedkar Nagar"},
  {"st": "34", "value": 645, "title": "Amethi"},
  {"st": "34", "value": 646, "title": "Amroha"},
  {"st": "34", "value": 647, "title": "Auraiya"},
  {"st": "34", "value": 648, "title": "Ayodhya"},
  {"st": "34", "value": 649, "title": "Azamgarh"},
  {"st": "34", "value": 650, "title": "Baghpat"},
  {"st": "34", "value": 651, "title": "Bahraich"},
  {"st": "34", "value": 652, "title": "Ballia"},
  {"st": "34", "value": 653, "title": "Balrampur"},
  {"st": "34", "value": 654, "title": "Banda"},
  {"st": "34", "value": 655, "title": "Barabanki"},
  {"st": "34", "value": 656, "title": "Bareilly"},
  {"st": "34", "value": 657, "title": "Basti"},
  {"st": "34", "value": 658, "title": "Bhadohi"},
  {"st": "34", "value": 659, "title": "Bijnor"},
  {"st": "34", "value": 660, "title": "Budaun"},
  {"st": "34", "value": 661, "title": "Bulandshahr"},
  {"st": "34", "value": 662, "title": "Chandauli"},
  {"st": "34", "value": 663, "title": "Chitrakoot"},
  {"st": "34", "value": 664, "title": "Deoria"},
  {"st": "34", "value": 665, "title": "Etah"},
  {"st": "34", "value": 666, "title": "Etawah"},
  {"st": "34", "value": 667, "title": "Farrukhabad"},
  {"st": "34", "value": 668, "title": "Fatehpur"},
  {"st": "34", "value": 669, "title": "Firozabad"},
  {"st": "34", "value": 670, "title": "Gautam Buddha Nagar"},
  {"st": "34", "value": 671, "title": "Ghaziabad"},
  {"st": "34", "value": 672, "title": "Ghazipur"},
  {"st": "34", "value": 673, "title": "Gonda"},
  {"st": "34", "value": 674, "title": "Gorakhpur"},
  {"st": "34", "value": 675, "title": "Hamirpur"},
  {"st": "34", "value": 676, "title": "Hapur"},
  {"st": "34", "value": 677, "title": "Hardoi"},
  {"st": "34", "value": 678, "title": "Hathras"},
  {"st": "34", "value": 679, "title": "Jalaun"},
  {"st": "34", "value": 680, "title": "Jaunpur"},
  {"st": "34", "value": 681, "title": "Jhansi"},
  {"st": "34", "value": 682, "title": "Kannauj"},
  {"st": "34", "value": 683, "title": "Kanpur Dehat"},
  {"st": "34", "value": 684, "title": "Kanpur Nagar"},
  {"st": "34", "value": 685, "title": "Kasganj"},
  {"st": "34", "value": 686, "title": "Kaushambi"},
  {"st": "34", "value": 687, "title": "Kheri"},
  {"st": "34", "value": 688, "title": "Kushinagar"},
  {"st": "34", "value": 689, "title": "Lalitpur"},
  {"st": "34", "value": 690, "title": "Lucknow"},
  {"st": "34", "value": 691, "title": "Maharajganj"},
  {"st": "34", "value": 692, "title": "Mahoba"},
  {"st": "34", "value": 693, "title": "Mainpuri"},
  {"st": "34", "value": 694, "title": "Mathura"},
  {"st": "34", "value": 695, "title": "Mau"},
  {"st": "34", "value": 696, "title": "Meerut"},
  {"st": "34", "value": 697, "title": "Mirzapur"},
  {"st": "34", "value": 698, "title": "Moradabad"},
  {"st": "34", "value": 699, "title": "Muzaffarnagar"},
  {"st": "34", "value": 700, "title": "Pilibhit"},
  {"st": "34", "value": 701, "title": "Pratapgarh"},
  {"st": "34", "value": 702, "title": "Prayagraj"},
  {"st": "34", "value": 703, "title": "Raebareli"},
  {"st": "34", "value": 704, "title": "Rampur"},
  {"st": "34", "value": 705, "title": "Saharanpur"},
  {"st": "34", "value": 706, "title": "Sambhal"},
  {"st": "34", "value": 707, "title": "Sant Kabir Nagar"},
  {"st": "34", "value": 708, "title": "Shahjahanpur"},
  {"st": "34", "value": 709, "title": "Shamli"},
  {"st": "34", "value": 710, "title": "Shravasti"},
  {"st": "34", "value": 711, "title": "Siddharthnagar"},
  {"st": "34", "value": 712, "title": "Sitapur"},
  {"st": "34", "value": 713, "title": "Sonbhadra"},
  {"st": "34", "value": 714, "title": "Sultanpur"},
  {"st": "34", "value": 715, "title": "Unnao"},
  {"st": "34", "value": 716, "title": "Varanasi"},
  {"st": "35", "title": "Alipurduar", "value": 717},
  {"st": "35", "title": "Bankura", "value": 718},
  {"st": "35", "title": "Birbhum", "value": 719},
  {"st": "35", "title": "Cooch Behar", "value": 720},
  {"st": "35", "title": "Dakshin Dinajpur", "value": 721},
  {"st": "35", "title": "Darjeeling", "value": 722},
  {"st": "35", "title": "Hooghly", "value": 723},
  {"st": "35", "title": "Howrah", "value": 724},
  {"st": "35", "title": "Jalpaiguri", "value": 725},
  {"st": "35", "title": "Jhargram", "value": 726},
  {"st": "35", "title": "Kalimpong", "value": 727},
  {"st": "35", "title": "Kolkata", "value": 728},
  {"st": "35", "title": "Malda", "value": 729},
  {"st": "35", "title": "Murshidabad", "value": 730},
  {"st": "35", "title": "Nadia", "value": 731},
  {"st": "35", "title": "North 24 Parganas", "value": 731},
  {"st": "35", "title": "Paschim Bardhaman", "value": 732},
  {"st": "35", "title": "Paschim Medinipur", "value": 733},
  {"st": "35", "title": "Purba Bardhaman", "value": 734},
  {"st": "35", "title": "Purba Medinipur", "value": 735},
  {"st": "35", "title": "Purulia", "value": 736},
  {"st": "35", "title": "South 24 Parganas", "value": 737},
  {"st": "35", "title": "Uttar Dinajpur", "value": 738},
];
